### PR TITLE
Little improvement for LowContrastMode settings

### PR DESCRIPTION
**Pull request by dayanch96**

### CODE REVIEW

**Comment by arichorn** [comment]
You already beaten me to it, but there is a problem, I don’t want users to be forced with this on by default since I’m seeing “Default UI” I made a toggle to turn off/on the tweak LowContrastMode

**Comment by dayanch96** [comment]
> You already beaten me to it, but there is a problem, I don’t want users to be forced with this on by default since I’m seeing “Default UI” I made a toggle to turn off/on the tweak LowContrastMode

Default ui means default color for low contrast mode. activating global boolean displays it.

**Comment by arichorn** [comment]
> Default ui means default color for low contrast mode. activating global boolean displays it.

oh so “White UI (a.k.a the real Default UI)” is gone.

**Comment by dayanch96** [comment]
> > Default ui means default color for low contrast mode. activating global boolean displays it.
> 
> oh so “White UI (a.k.a the real Default UI)” is gone.

yup. its enought to turn off lowcontrastmodebool for youtube’s stock UI

**Comment by arichorn** [comment]
Oh and also I forgot to say that the tweak LowContrastMode is in beta because there are new issues with the new UI that was added in newer YouTube versions from 2022-present, since YouTube added rounded buttons in the video player I wasn’t able to modify the texts in them which means I couldn’t fix it so for me this tweak works best on 16.45.6-older. But glad you’re helping out on this repository. 👍

**Comment by arichorn** [comment]
But here I’ll merge the pull request

**Comment by arichorn** [comment]
https://github.com/arichorn/CercubePlusExtra/actions/runs/4095535473/jobs/7062517029 ?

**Comment by dayanch96** [comment]
> https://github.com/arichorn/CercubePlusExtra/actions/runs/4095535473/jobs/7062517029 ?

https://github.com/arichorn/CercubePlusExtra/blob/main/Settings.xm#L591

9C154057-7570-49DD-988B-DBEB24211589

**Pull request merged**
